# =============================================================
# TFG-OpenVPN — Configuracion LDAP para OpenVPN
# Autor: Said Rais
# =============================================================

<LDAP>
    # Servidor LDAP
    URL             ldap://localhost:389
    BindDN          cn=vpnbind,ou=serviceaccounts,dc=empresa,dc=local
    Password        Cambiame123
    Timeout         15
    TLSEnable       no
    FollowReferrals no
</LDAP>

<Authorization>
    # Donde buscar usuarios
    BaseDN          dc=domainsaid,dc=internal
    SearchFilter    (cn=%u)
    RequireGroup    true

    <Group>
        # Solo usuarios del grupo vpnusers tienen acceso
        BaseDN      dc=domainsaid,dc=internal
        SearchFilter (cn=vpnusers)
        MemberAttribute member
    </Group>
</Authorization>
